### ISSUE TITLE
queue_up_workflow and wait_for_workflow

### ISSUE THREAD

**Issue by teocomi** [roopakv/orbs#76]
Hiya!

I've been spending several hours trying to get either `queue_up_workflow` or `wait_for_workflow` working in my pipeline, but I keep getting a `Exited with code exit status 22`. Here's some of the code I'm using:

```
workflows:
 installers:
    jobs:
      ...

  deployment:
    jobs:
      - swissknife/queue_up_workflow:
          workflow-name: "installers"
      - deploy:
          requires: 
            - swissknife/queue_up_workflow
```

**Comment by sijangurung** [comment]
+1

**Comment by roopakv** [comment]
@sijangurung @teocomi I use this in our pipelines and a few other folks do too. So I am not sure exactly why it si failing. do you have any logs or repro steps I can look at

**Comment by sijangurung** [comment]
Can you please show us a little more detailed config.yml where you have implemented queue_up_workflow. Thanks in advance
@roopakv

**Comment by roopakv** [comment]
@sijangurung i can't post the whole workflow but I will post a snapshot.

```
workflows:
  production:
        jobs:
            - swissknife/queue_up_workflow:
                max-wait-time: "1800"
                workflow-name: ^(staging|production)$
            - test-something:
                context: some-secrets
                name: Some tests
            - test-something2:
                name: something2 tests
            - test-after-queue:
                name: Tests that need to be queued
                requires:
                    - swissknife/queue_up_workflow
```

here all `test-after-queue` runs will be queued.

**Comment by sijangurung** [comment]
My usecase is workflow2 should wait for workflow1 and workflow3 should wait for workflow2
```
workflows:
     workflow1:
           ...
           jobs:
             - common jobs
             - some conditions 
    workflow2:
           ...
           jobs: 
                - swissknife/queue_up_workflow:
                             workflow-name: "workflow1"
               - some other job               
    workflow3:
           ...
           jobs: 
                - swissknife/queue_up_workflow:
                             workflow-name: "workflow2"
```
                             
This won't work @roopakv

**Comment by roopakv** [comment]
@sijangurung seems like you have some bugs i the above, but it should work

```
workflows:
     workflow1:
           ...
           jobs:
             - common jobs
             - some conditions 
    workflow2:
           ...
           jobs: 
                - swissknife/queue_up_workflow:
                             workflow-name: "workflow1"
               - some other job:
                    requires:
                    - swissknife/queue_up_workflow              
    workflow3:
           ...
           jobs: 
                - swissknife/queue_up_workflow:
                             workflow-name: "workflow2"
                - some-job:
                     require: swissknife/queue_up_workflow
```
